# see https://docs.openshift.com/container-platform/4.7/storage/dynamic-provisioning.html#azure-file-definition_dynamic-provisioning
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: 'system:azure-cloud-provider'
rules:
- apiGroups: ['']
  resources: ['secrets']
  verbs:     ['get','create']
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: create-azure-secrets
subjects:
  - kind: ServiceAccount
    name: persistent-volume-binder
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: 'system:azure-cloud-provider'
  apiGroup: rbac.authorization.k8s.io